name = "rook"

[[export]]
path = "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
module = "ceph"
group = "ceph.rook.io"
version = "v1"

[[dependency]]
name = "kubernetes"
version = "1.30"

[[extern]]
path = "k8s.io/apimachinery/pkg/apis/meta/v1"
package = "kubernetes"
module = "meta"
group = "meta"
version = "v1"

[[extern]]
path = "k8s.io/api/core/v1"
package = "kubernetes"
module = "core"
group = ""
version = "v1"
