name = "prometheus"

[[export]]
path = "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
group = "monitoring.coreos.com"
version = "v1"

[[export]]
path = "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1"
group = "monitoring.coreos.com"
version = "v1beta1"

[[export]]
path = "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1"
group = "monitoring.coreos.com"
version = "v1alpha1"

[[dependency]]
name = "kubernetes"
version = "1.30"

[[extern]]
path = "k8s.io/apimachinery/pkg/apis/meta/v1"
package = "kubernetes"
module = "meta"
group = "meta"
version = "v1"

[[extern]]
path = "k8s.io/api/apps/v1"
package = "kubernetes"
module = "apps"
group = "apps"
version = "v1"

[[extern]]
path = "k8s.io/api/core/v1"
package = "kubernetes"
module = "core"
group = ""
version = "v1"

[[extern]]
path = "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
package = "kubernetes"
module = "apiextensions"
group = "apiextensions.k8s.io"
version = "v1"

[[extern]]
path = "k8s.io/apimachinery/pkg/api/resource"
package = "kubernetes"
module = "meta"
group = "meta"
version = "v1"
