name = "aws/iam"

[[export]]
path = "github.com/aws-controllers-k8s/iam-controller/apis/v1alpha1"
group = "iam.services.k8s.aws"
version = "v1alpha1"
explicit-null = true
prune = true

[[dependency]]
name = "kubernetes"
version = "1.29"

[[dependency]]
name = "aws/ack"
version = "0.34"

[[extern]]
path = "k8s.io/apimachinery/pkg/apis/meta/v1"
package = "kubernetes"
module = "meta"
group = "meta"
version = "v1"

[[extern]]
path = "k8s.io/api/core/v1"
package = "kubernetes"
module = "core"
group = ""
version = "v1"

[[extern]]
package = "aws/ack"
path = "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
group = "services.k8s.aws"
module = "core"
version = "v1alpha1"
