name = "kubernetes"

[[export]]
path = "k8s.io/api/admission/v1"
module = "admission"
group = "admission.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/admission/v1beta1"
module = "admission"
group = "admission.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/admissionregistration/v1"
module = "admissionregistration"
group = "admissionregistration.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/admissionregistration/v1beta1"
module = "admissionregistration"
group = "admissionregistration.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/apidiscovery/v2"
module = "apidiscovery"
group = "apidiscovery.k8s.io"
version = "v2"

[[export]]
path = "k8s.io/api/apidiscovery/v2beta1"
module = "apidiscovery"
group = "apidiscovery.k8s.io"
version = "v2beta1"

[[export]]
path = "k8s.io/api/apps/v1"
module = "apps"
group = "apps"
version = "v1"

[[export]]
path = "k8s.io/api/apps/v1beta1"
module = "apps"
group = "apps"
version = "v1beta1"

[[export]]
path = "k8s.io/api/apps/v1beta2"
module = "apps"
group = "apps"
version = "v1beta2"

[[export]]
path = "k8s.io/api/authentication/v1"
module = "authentication"
group = "authentication.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/authentication/v1beta1"
module = "authentication"
group = "authentication.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/authorization/v1"
module = "authorization"
group = "authorization.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/authorization/v1beta1"
module = "authorization"
group = "authorization.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/autoscaling/v1"
module = "autoscaling"
group = "autoscaling"
version = "v1"

[[export]]
path = "k8s.io/api/autoscaling/v2"
module = "autoscaling"
group = "autoscaling"
version = "v2"

[[export]]
path = "k8s.io/api/autoscaling/v2beta1"
module = "autoscaling"
group = "autoscaling"
version = "v2beta1"

[[export]]
path = "k8s.io/api/autoscaling/v2beta2"
module = "autoscaling"
group = "autoscaling"
version = "v2beta2"

[[export]]
path = "k8s.io/api/batch/v1"
module = "batch"
group = "batch"
version = "v1"

[[export]]
path = "k8s.io/api/batch/v1beta1"
module = "batch"
group = "batch"
version = "v1beta1"

[[export]]
path = "k8s.io/api/certificates/v1"
module = "certificates"
group = "certificates.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/certificates/v1beta1"
module = "certificates"
group = "certificates.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/coordination/v1"
module = "coordination"
group = "coordination.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/coordination/v1beta1"
module = "coordination"
group = "coordination.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/core/v1"
module = "core"
group = ""
version = "v1"

[[export]]
path = "k8s.io/api/discovery/v1"
module = "discovery"
group = "discovery.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/discovery/v1beta1"
module = "discovery"
group = "discovery.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/events/v1"
module = "events"
group = "events.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/events/v1beta1"
module = "events"
group = "events.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/extensions/v1beta1"
module = "extensions"
group = "extensions"
version = "v1beta1"

[[export]]
path = "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
module = "apiextensions"
group = "apiextensions.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/kube-aggregator/pkg/apis/apiregistration/v1"
module = "apiregistration"
group = "apiregistration.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1"
module = "apiregistration"
group = "apiregistration.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/flowcontrol/v1"
module = "apiserver/flowcontrol"
group = "flowcontrol.apiserver.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/flowcontrol/v1beta1"
module = "apiserver/flowcontrol"
group = "flowcontrol.apiserver.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/flowcontrol/v1beta2"
module = "apiserver/flowcontrol"
group = "flowcontrol.apiserver.k8s.io"
version = "v1beta2"

[[export]]
path = "k8s.io/api/flowcontrol/v1beta3"
module = "apiserver/flowcontrol"
group = "flowcontrol.apiserver.k8s.io"
version = "v1beta3"

[[export]]
path = "k8s.io/apimachinery/pkg/apis/meta/v1"
module = "meta"
group = "meta"
version = "v1"

[[export]]
path = "k8s.io/apimachinery/pkg/api/resource"
module = "meta/resource"
group = "meta"
version = "v1"
merge = { module = "meta", include = ["Quantity"] }

[[export]]
path = "k8s.io/apimachinery/pkg/types"
module = "meta/types"
group = "meta"
version = "v1"
merge = { module = "meta", include = ["NodeName", "PatchType", "UID"] }

[[export]]
path = "k8s.io/api/networking/v1"
module = "networking"
group = "networking.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/networking/v1beta1"
module = "networking"
group = "networking.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/node/v1"
module = "node"
group = "node.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/node/v1beta1"
module = "node"
group = "node.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/policy/v1"
module = "policy"
group = "policy"
version = "v1"

[[export]]
path = "k8s.io/api/policy/v1beta1"
module = "policy"
group = "policy"
version = "v1beta1"

[[export]]
path = "k8s.io/api/rbac/v1"
module = "authorization/rbac"
group = "rbac.authorization.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/rbac/v1beta1"
module = "authorization/rbac"
group = "rbac.authorization.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/scheduling/v1"
module = "scheduling"
group = "scheduling.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/scheduling/v1beta1"
module = "scheduling"
group = "scheduling.k8s.io"
version = "v1beta1"

[[export]]
path = "k8s.io/api/storage/v1"
module = "storage"
group = "storage.k8s.io"
version = "v1"

[[export]]
path = "k8s.io/api/storage/v1beta1"
module = "storage"
group = "storage.k8s.io"
version = "v1beta1"
