SOURCE ?= https://github.com/kubernetes/kubernetes.git
REF ?= master

PACKAGES = k8s.io/api/... k8s.io/apimachinery/... k8s.io/apiextensions-apiserver/pkg/apis/... k8s.io/kube-aggregator/pkg/apis/...

include ../package.mk
