name = "component-base"

[[export]]
path = "k8s.io/component-base/logs/api/v1"
group = "logs.component.k8s.io"
module = "logs"
version = "v1"
exclude = ["LoggingOptions", "RuntimeControl"]

[[export]]
path = "k8s.io/component-base/tracing/api/v1"
module = "tracing"
group = "tracing.component.k8s.io"
version = "v1"

[[dependency]]
name = "kubernetes"
version = "1.30"

[[extern]]
path = "k8s.io/apimachinery/pkg/apis/meta/v1"
package = "kubernetes"
module = "meta"
group = "meta"
version = "v1"
